# Generated by Django 3.0.7 on 2020-06-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naptar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='szolgaltatasaink',
            field=models.CharField(choices=[('ZV', 'Zene varázsa'), ('KD', 'KElet divatja'), ('EF', 'Egzotikus fűszerkalauz'), ('LH', 'Lélek Hangja'), ('ZK', 'Szerencsét hozó zarándokkörút'), ('KK', 'Krisna-völgyi Körtúra'), ('OT', 'Öko Tanösvény'), ('EB', 'Ebéd'), ('ET', 'Ételkóstoló')], default='KK', max_length=2),
        ),
    ]
