# Generated by Django 3.0.7 on 2020-06-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naptar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='letrehozva',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='modositva',
            field=models.DateField(blank=True),
        ),
    ]
