# Generated by Django 3.0.7 on 2020-06-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naptar', '0002_auto_20200622_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='letrehozva',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='modositva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
